name: emurestapi
channels:
- conda-forge
dependencies:
- python>=3.11,<3.14
- pip
- ipykernel
- jupyter
- requests-cache
- pip:
  - git+https://github.com/adamancer/xmu.git@dev
  - git+https://github.com/adamancer/nmnh_ms_tools.git
